## MACHINE LEARNING PRACTICALS
### KNN CLASSIFICATION
### Raj Khatri 
### AC-1235

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns


LOAD DATASET

In [2]:
df = sns.load_dataset('iris')


In [3]:
X = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values


Splitting the dataset into Train and Test set

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0)


In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [6]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(X_train, y_train)


KNeighborsClassifier()

In [8]:
y_pred = classifier.predict(X_test)


Train the KNN Classification model on the training set and predicting the value

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("F1 score: ", f1_score(y_pred, y_test, average="weighted"))


[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
Accuracy:  0.9777777777777777
F1 score:  0.9776121463077985


In [10]:
precision = precision_score(y_test, y_pred, average='micro')
recall = recall_score(y_test, y_pred, average='micro')
print("Precision: ", precision*100)
print("Recall: ", recall*100)


Precision:  97.77777777777777
Recall:  97.77777777777777
