## MACHINE LEARNING PRACTICALS
### LOGISTIC REGRESSION CLASSIFICATION
### Raj Khatri 
### AC-1235

Import libraries

In [8]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


Load Dataset

In [9]:
df = sns.load_dataset('iris')


In [10]:
X = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values


In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0)


In [12]:
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [13]:
y_pred = classifier.predict(X_test)


Calculating the accuracy, precision and recall

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("F1 score: ", f1_score(y_pred, y_test, average="weighted"))


[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
Accuracy:  0.9777777777777777
F1 score:  0.9776121463077985


In [15]:
precision = precision_score(y_test, y_pred, average='micro')
recall = recall_score(y_test, y_pred, average='micro')
print("Precision: ", precision)
print("Recall: ", recall)


Precision:  0.9777777777777777
Recall:  0.9777777777777777
