IMPORT LIBRARIES

In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns


LOAD DATASET

In [17]:
df = sns.load_dataset('iris')


In [18]:
X = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values


Splitting the dataset into Train and Test set

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0)


Train the Naive Bayes Classification model on the training set and predicting the value

In [20]:
classifier = GaussianNB()
classifier.fit(X_train, y_train)


GaussianNB()

In [21]:
y_pred = classifier.predict(X_test)


In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("F1 score: ", f1_score(y_pred, y_test, average="weighted"))


[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
Accuracy:  1.0
F1 score:  1.0


In [23]:
precision = precision_score(y_test, y_pred, average='micro')
recall = recall_score(y_test, y_pred, average='micro')
print("Precision: ", precision*100)
print("Recall: ", recall*100)


Precision:  100.0
Recall:  100.0
