# Q2) Download any Dataset from ML UCI repository and apply all Preprocessing Tools for:
1)Handling Missing Data

2)Encoding Independent and Dependent Variables

3)Splitting the Dataset into the Training and Test Set

4)Feature Scaling 

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
df = pd.read_csv('/content/car.data')
df

buying  maint  doors  persons lug_boot safety  Class
0     vhigh  vhigh      2        2    small    low  unacc
1     vhigh  vhigh      2        2    small    med  unacc
2     vhigh  vhigh      2        2    small   high  unacc
3     vhigh  vhigh      2        2      med    low  unacc
4     vhigh  vhigh      2        2      med    med  unacc
...     ...    ...    ...      ...      ...    ...    ...
1723    low    low      5        5      med    med   good
1724    low    low      5        5      med   high  vgood
1725    low    low      5        5      big    low  unacc
1726    low    low      5        5      big    med   good
1727    low    low      5        5      big   high  vgood

[1728 rows x 7 columns]

In [ ]:
x= df.iloc[:,-1].values #dependent
x

array(['unacc', 'unacc', 'unacc', ..., 'unacc', 'good', 'vgood'],
      dtype=object)

In [ ]:
y= df.iloc[:,:-1].values #indepent
y

array([['vhigh', 'vhigh', 2, 2, 'small', 'low'],
       ['vhigh', 'vhigh', 2, 2, 'small', 'med'],
       ['vhigh', 'vhigh', 2, 2, 'small', 'high'],
       ...,
       ['low', 'low', 5, 5, 'big', 'low'],
       ['low', 'low', 5, 5, 'big', 'med'],
       ['low', 'low', 5, 5, 'big', 'high']], dtype=object)

## Checking Nan values

In [ ]:
df.isna().sum()   #no null values

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
Class       0
dtype: int64

In [ ]:
#df['Class'].fillna(value=df['Class'].mean(), inplace=True)

## Encoding categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0,1,4,5])], remainder = 'passthrough') #for independent

In [ ]:
y = np.array(ct.fit_transform(y))
y

array([[0.0, 0.0, 0.0, ..., 0.0, 2, 2],
       [0.0, 0.0, 0.0, ..., 1.0, 2, 2],
       [0.0, 0.0, 0.0, ..., 0.0, 2, 2],
       ...,
       [0.0, 1.0, 0.0, ..., 0.0, 5, 5],
       [0.0, 1.0, 0.0, ..., 1.0, 5, 5],
       [0.0, 1.0, 0.0, ..., 0.0, 5, 5]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
l = LabelEncoder()
x = l.fit_transform(x)
x

array([2, 2, 2, ..., 2, 1, 3])

## Splitting data

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_test)

[2 0 2 2 2 0 2 2 0 2 0 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 0 3 2 2 2 2 2 2
 2 0 2 2 0 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2 2 2 3 2 1 2 2 2 2 0 2 2 2 2 2
 1 2 2 0 0 0 0 0 1 2 2 3 0 2 0 2 0 2 2 2 2 0 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2
 0 2 2 0 0 2 1 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 3 2 2 3 2 2 2 2 0 0 2 0 2 0
 2 2 2 2 2 2 1 0 0 2 2 2 2 2 0 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 1 2 2 2 2 0 2 2 3 2 2 0 2 2 2 2 2 0 2 2 2 2 2 2 3 0 0 2 0 2 3 2 2 2 2 2 2
 2 0 2 2 2 2 2 2 0 2 2 2 1 0 2 2 0 2 2 2 0 1 2 0 2 0 2 2 2 2 1 2 2 0 0 2 2
 2 2 2 2 0 2 2 2 1 2 2 2 0 1 2 2 2 0 2 2 1 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2
 2 3 2 2 2 2 2 2 2 0 0 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 3 0 0 2 0 0 2 2 0 1 2
 2 2 2 0 2 2 0 0 2 3 2 2 2]


In [ ]:
print(X_train)

[1 0 2 ... 0 2 2]


In [ ]:
print(Y_test)

[[0.0 0.0 1.0 ... 0.0 3 5]
 [1.0 0.0 0.0 ... 1.0 3 5]
 [1.0 0.0 0.0 ... 1.0 5 2]
 ...
 [0.0 0.0 0.0 ... 0.0 4 2]
 [0.0 0.0 0.0 ... 1.0 3 5]
 [0.0 0.0 0.0 ... 1.0 5 4]]


In [ ]:
print(Y_train)

[[0.0 1.0 0.0 ... 1.0 4 4]
 [1.0 0.0 0.0 ... 1.0 5 4]
 [0.0 0.0 0.0 ... 0.0 5 2]
 ...
 [0.0 0.0 1.0 ... 1.0 2 4]
 [0.0 0.0 0.0 ... 1.0 2 5]
 [0.0 0.0 1.0 ... 0.0 5 2]]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler #feature scaling was not needed still done to show steps
sc = StandardScaler()

Y_train[:, -2:] = sc.fit_transform(Y_train[:, -2:])

Y_test[:, -2:] = sc.transform(Y_test[:, -2:])

In [ ]:
print(Y_train)

[[0.0 1.0 0.0 ... 1.0 0.44967095969958154 0.26731854823180684]
 [1.0 0.0 0.0 ... 1.0 1.3399936907953147 0.26731854823180684]
 [0.0 0.0 0.0 ... 0.0 1.3399936907953147 -1.3530070379802859]
 ...
 [0.0 0.0 1.0 ... 1.0 -1.3309745024918849 0.26731854823180684]
 [0.0 0.0 0.0 ... 1.0 -1.3309745024918849 1.0774813413378532]
 [0.0 0.0 1.0 ... 0.0 1.3399936907953147 -1.3530070379802859]]


In [ ]:

print(Y_test)

[[0.0 0.0 1.0 ... 0.0 -0.44065177139615164 1.0774813413378532]
 [1.0 0.0 0.0 ... 1.0 -0.44065177139615164 1.0774813413378532]
 [1.0 0.0 0.0 ... 1.0 1.3399936907953147 -1.3530070379802859]
 ...
 [0.0 0.0 0.0 ... 0.0 0.44967095969958154 -1.3530070379802859]
 [0.0 0.0 0.0 ... 1.0 -0.44065177139615164 1.0774813413378532]
 [0.0 0.0 0.0 ... 1.0 1.3399936907953147 0.26731854823180684]]
