# Q3)(b) Implement a Multiple Linear Regression Model on a Dataset.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Multiple Linear Regression

In [ ]:
df = pd.read_excel('/content/Real estate valuation data set.xlsx')
df

X1 transaction date  ...  Y house price of unit area
0            2012.916667  ...                        37.9
1            2012.916667  ...                        42.2
2            2013.583333  ...                        47.3
3            2013.500000  ...                        54.8
4            2012.833333  ...                        43.1
..                   ...  ...                         ...
409          2013.000000  ...                        15.4
410          2012.666667  ...                        50.0
411          2013.250000  ...                        40.6
412          2013.000000  ...                        52.5
413          2013.500000  ...                        63.9

[414 rows x 7 columns]

In [ ]:
dep= df.iloc[:,-1].values #dependent
dep

array([ 37.9,  42.2,  47.3,  54.8,  43.1,  32.1,  40.3,  46.7,  18.8,
        22.1,  41.4,  58.1,  39.3,  23.8,  34.3,  50.5,  70.1,  37.4,
        42.3,  47.7,  29.3,  51.6,  24.6,  47.9,  38.8,  27. ,  56.2,
        33.6,  47. ,  57.1,  22.1,  25. ,  34.2,  49.3,  55.1,  27.3,
        22.9,  25.3,  47.7,  46.2,  15.9,  18.2,  34.7,  34.1,  53.9,
        38.3,  42. ,  61.5,  13.4,  13.2,  44.2,  20.7,  27. ,  38.9,
        51.7,  13.7,  41.9,  53.5,  22.6,  42.4,  21.3,  63.2,  27.7,
        55. ,  25.3,  44.3,  50.7,  56.8,  36.2,  42. ,  59. ,  40.8,
        36.3,  20. ,  54.4,  29.5,  36.8,  25.6,  29.8,  26.5,  40.3,
        36.8,  48.1,  17.7,  43.7,  50.8,  27. ,  18.3,  48. ,  25.3,
        45.4,  43.2,  21.8,  16.1,  41. ,  51.8,  59.5,  34.6,  51. ,
        62.2,  38.2,  32.9,  54.4,  45.7,  30.5,  71. ,  47.1,  26.6,
        34.1,  28.4,  51.6,  39.4,  23.1,   7.6,  53.3,  46.4,  12.2,
        13. ,  30.6,  59.6,  31.3,  48. ,  32.5,  45.5,  57.4,  48.6,
        62.9,  55. ,

In [ ]:
inp= df.iloc[:,:-1].values #indepent
inp

array([[2012.92,   32.  ,   84.88,   10.  ,   24.98,  121.54],
       [2012.92,   19.5 ,  306.59,    9.  ,   24.98,  121.54],
       [2013.58,   13.3 ,  561.98,    5.  ,   24.99,  121.54],
       ...,
       [2013.25,   18.8 ,  390.97,    7.  ,   24.98,  121.54],
       [2013.  ,    8.1 ,  104.81,    5.  ,   24.97,  121.54],
       [2013.5 ,    6.5 ,   90.46,    9.  ,   24.97,  121.54]])

## Checking Nan

In [ ]:
df.isna().sum() #no null values

X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

## Splitting

In [ ]:
from sklearn.model_selection import train_test_split
inp_train, inp_test, dep_train, dep_test = train_test_split(inp, dep, test_size = 0.2, random_state = 1)

## Training

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(inp_train, dep_train)

LinearRegression()

## Predecting test values and comparing with actual value

In [ ]:
dep_pred = regressor.predict(inp_test)
np.set_printoptions(precision=2)

df_pred = pd.DataFrame({'actual value' : np.array(dep_test), 'predicted value' : dep_pred}).astype('int')
df_pred

actual value  predicted value
0             27               34
1             54               47
2             22               20
3             11               12
4             45               42
..           ...              ...
78            33               40
79            59               48
80            40               45
81            52               40
82            47               45

[83 rows x 2 columns]

In [ ]:
print(regressor.predict([[ 2013.583333 ,	5.1 ,	80.98450	, 7	, 24.98746 ,	121.54391]]))

[55.79]


## Coefficient and intercept

In [ ]:
print(regressor.coef_)
print(regressor.intercept_)

[ 5.72e+00 -2.49e-01 -4.94e-03  1.08e+00  2.27e+02 -3.57e+01]
-12803.289614298801
